# Generated by Django 4.1.2 on 2022-10-23 16:03

from django.db import migrations, models
import users.validator


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="birth_date",
            field=models.DateField(null=True, validators=[users.validator.check_age]),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=254,
                null=True,
                unique=True,
                validators=[users.validator.EmailCheckValidator],
            ),
        ),
    ]
